import {ethers} from "ethers";

const ORACLE_ACCESS_TYPE_CHAINLINK = 1

type OracleAccess = 1

type SetPairCommonParams = Array<{
    pairNumber: number,
    from: string,
    to: string,
    feed1: string,
    accessType: OracleAccess,
    pricePrintDecimal: number,
    feedPriceMultiplyDecimal: number,
    feedPriceDivideDecimal: number,
}>

const hardhatParam : SetPairCommonParams  =  [
    {
        pairNumber: 0,
        from: `BTC`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 2,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 6,
    },
    {
        pairNumber: 1,
        from: `ETH`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 2,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 6,
    },
    {
        pairNumber: 2,
        from: `BNB`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 2,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 6,
    },
    {
        pairNumber: 3,
        from: `SOL`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 2,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 6,
    },
    {
        pairNumber: 4,
        from: `XRP`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 4,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 4,
    },
    {
        pairNumber: 5,
        from: `TON`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 4,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 0,
    },
    {
        pairNumber: 6,
        from: `OKB`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 4,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 0,
    },
    {
        pairNumber: 7,
        from: `DOGE`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 4,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 4,
    },
    {
        pairNumber: 8,
        from: `SHIB`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 8,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 0,
    },
    {
        pairNumber: 9,
        from: `PEPE`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 10,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 0,
    },
]

const story4tParam : SetPairCommonParams =  [
    {
        pairNumber: 0,
        from: `BTC`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 2,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 0,
    },
    {
        pairNumber: 1,
        from: `ETH`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 2,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 0,
    },
    {
        pairNumber: 2,
        from: `BNB`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 2,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 0,
    },
    {
        pairNumber: 3,
        from: `SOL`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 2,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 0,
    },
    {
        pairNumber: 4,
        from: `XRP`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 4,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 0,
    },
    {
        pairNumber: 5,
        from: `TON`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 4,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 0,
    },
    {
        pairNumber: 6,
        from: `OKB`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 4,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 0,
    },
    {
        pairNumber: 7,
        from: `DOGE`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 4,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 0,
    },
    {
        pairNumber: 8,
        from: `SHIB`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 8,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 0,
    },
    {
        pairNumber: 9,
        from: `PEPE`,
        to: `USD`,
        feed1: ethers.ZeroAddress,
        accessType: ORACLE_ACCESS_TYPE_CHAINLINK,
        pricePrintDecimal: 10,
        feedPriceMultiplyDecimal: 0,
        feedPriceDivideDecimal: 0,

    },
]


export const setPairCommonParams = {
    hardhatParam : hardhatParam,
    story4tParam : story4tParam,
}
